### ISSUE TITLE
Not using tsconfig

### ISSUE THREAD

**Issue by eddyerburgh** [eddyerburgh/vue-jest#8] opened 2017-10-01 09:18 UTC
Typescript was not using a tsconfig

Original issue - https://github.com/vuejs/vue-test-utils/issues/47

This should be fixed in jest-vue 0.6.0.

**Comment by rndmerle** [comment] 2017-10-05 19:30
Thanks for taking the time to stab the issue.
I tried on the reproduction repo with jest-vue 0.6.0 (and then 0.7.0) and all other packages updated to latest version, and `npm test -- --no-cache` coughed this:
```
 TypeError: unknown: Cannot create property 'mappings' on string '{"version":3,"file":"module.js","sourceRoot":"","sources":["module.ts"],"names":[],"mappings":"AAKA,OAAO,GAAG,MAAM,WAAW,CAAC;AAE5B,eAAe;IACX,IAAI,EAAE,WAAW;IACjB,UAAU,EAAE;QACR,GAAG,KAAA;KACN;CACJ,CAAA"}'

      at File.mergeSourceMap (node_modules/babel-core/lib/transformation/file/index.js:481:25)
      at File.generate (node_modules/babel-core/lib/transformation/file/index.js:719:25)
      at File.transform (node_modules/babel-core/lib/transformation/file/index.js:554:17)
      at node_modules/babel-core/lib/transformation/pipeline.js:50:19
      at File.wrap (node_modules/babel-core/lib/transformation/file/index.js:564:16)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:47:17)
      at compileBabel (node_modules/jest-vue/lib/compilers/babel-compiler.js:36:21)
      at compileTypescript (node_modules/jest-vue/lib/compilers/typescript-compiler.js:44:10)
      at processScript (node_modules/jest-vue/lib/process.js:14:12)
      at Object.module.exports [as process] (node_modules/jest-vue/lib/process.js:27:18)


[jest-vue] Info: no .babelrc found, defaulting to default babel options
```
Not sure why it's calling babel.
I updated the reproduction repository with latest versions.

**Comment by cgodley** [comment] 2017-10-06 04:07
I had a similar problem and was able to fix it by editing `typescript-compiler.js` to pass the `inputSourceMap` to `compileBabel` as an object rather than a string:

```diff
- return compileBabel(res.outputText, res.sourceMapText)
+ return compileBabel(res.outputText, JSON.parse(res.sourceMapText))
```

**Comment by eddyerburgh** [comment] 2017-10-06 06:38
Are you able to make a PR @cgodley ?

**Comment by rndmerle** [comment] 2017-10-19 15:33
I'm really lacking time currently to dig anything deeper.
But on our real project we've a weird behavior.

Using `vue-test-utils@1.0.0-beta.2`, if I upgrade `jest-vue` from `0.5.6` to `0.8.1` it kills the component stubbing of `vue-test-utils`'s `mount()`.
We're mounting components but still manually stubbing some sub-components. It works nicely with `0.5.6`, but, when upgrading, all sub-components are mounting despite the stubbing.
I wish I had the time to put a reproduction up, but not right now sorry.

**Comment by blake-newman** [comment] 2017-10-20 17:00
This should be fixed with https://github.com/vuejs/vue-test-utils/pull/115

I have also noticed that there is some issues with newer versions of jest where things where auto mocked. 

Here is my configuration for further reference... 

```
"jest": {
    "moduleFileExtensions": ["js", "json", "ts", "tsx", "vue"],
    "testRegex": "(/__tests__/.*|(\\.|/)test)\\.(tsx?)$",
    "modulePaths": ["<rootDir>/src/"],
    "moduleDirectories": ["node_modules", "<rootDir>/src/"],
    "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
      "^.+\\.vue?$": "<rootDir>/node_modules/jest-vue"
    },
    "verbose": true,
    "mapCoverage": true
}
```

**Comment by rndmerle** [comment] 2017-11-13 13:09
I took the time to update and test. It seems to be working fine for me.
Thanks!

**Closed** 2017-11-13 13:43 UTC
